ALTER TABLE phase1b_runs DROP CONSTRAINT IF EXISTS phase1b_runs_status_check;
ALTER TABLE phase1b_runs ADD CONSTRAINT phase1b_runs_status_check CHECK (status IN (
  'RUNNING', 'READY_FOR_HUMAN_REVIEW', 'REVISE_REQUIRED',
  'UNREVIEWED', 'BUDGET_EXCEEDED', 'ATTRIBUTION_BLOCKED',
  'DRAFT_GENERATION_FAILED', 'FAILED', 'CANCELLED', 'INTERRUPTED'
));
